### ISSUE TITLE
bad argument to paris

### ISSUE THREAD

**Issue by Mte90** [roobert/search-replace.nvim#1]
![immagine](https://user-images.githubusercontent.com/403283/210397931-cc18a57c-a6cf-4a70-95f1-4d617d43f7cb.png)

With the latest nvim nightly.

**Comment by roobert** [comment]
Thank you for opening an issue, please update and retry!

**Comment by roobert** [comment]
Pretty sure this issue is fixed, if not, please re-open the issue and happy to help!

**Comment by Mte90** [comment]
Sorry for the delay but I use neovim in office, the fix... fixed :-)
