### ISSUE TITLE
`SearchReplaceSingleBufferVisualSelection` not working

### ISSUE THREAD

**Issue by charliie-dev** [roobert/search-replace.nvim#2]
I'm not sure how to map this command. In the readme, it said
> lvim.keys.visual_block_mode["<C-r>"] = [[<CMD>SearchReplaceSingleBufferVisualSelection<CR>]]

But after I mapped it with 
```lua
vim.api.nvim_set_keymap("v", "<C-r>", "<cmd>SearchReplaceSingleBufferVisualSelection<cr>", { noremap = true, silent = true, nowait = true })
```
, and then I visual-selected a block and hit `<C-r>`, there's a message shows 
> search-replace does not support visual-blockwise selections

. However, in [the gif](https://user-images.githubusercontent.com/226654/210175210-0da9063b-e933-451d-bc90-2405ad9e03f0.gif), this seems doable.

I'm not sure if I misunderstood your instruction or it's a bug, thanks for your help!

**Comment by charliie-dev** [comment]
Also, I couldn't get the quickfix panel to pop-up, is that another plugin?
![圖片](https://user-images.githubusercontent.com/32497323/210913947-57d4f917-452a-4614-a363-0ceb0e315d6b.png)

**Comment by roobert** [comment]
> I'm not sure how to map this command. In the readme, it said
> 
> > lvim.keys.visual_block_mode[""] = [[SearchReplaceSingleBufferVisualSelection]]
> 
> But after I mapped it with
> 
> ```lua
> vim.api.nvim_set_keymap("v", "<C-r>", "<cmd>SearchReplaceSingleBufferVisualSelection<cr>", { noremap = true, silent = true, nowait = true })
> ```
> 
> , and then I visual-selected a block and hit `<C-r>`, there's a message shows
> 
> > search-replace does not support visual-blockwise selections
> 
> . However, in [the gif](https://user-images.githubusercontent.com/226654/210175210-0da9063b-e933-451d-bc90-2405ad9e03f0.gif), this seems doable.
> 
> I'm not sure if I misunderstood your instruction or it's a bug, thanks for your help!

Hi Charles, no problem!

The gif you mentioned shows the usage of `SearchReplaceWithinVisualSelectionCWord` rather than `SearchReplaceSingleBufferVisualSelection`. In my config I use `ctrl-b` to execute this to search across a visual-block with the value of CWord as the search parameter.

`SearchReplaceSingleBufferVisualSelection` is slightly different - it is a command to use visual char-wise (i.e: a visual selection within a single line) to highlight a selection of characters that can then be executed to bring up search with the selection of the highlight as the search parameter. Here's a demo of it: https://user-images.githubusercontent.com/226654/210175020-aaa1a6fa-7fb8-4d87-ade6-20fa391e1a57.gif 

Hope this helps!

**Comment by roobert** [comment]
> Also, I couldn't get the quickfix panel to pop-up, is that another plugin? ![圖片](https://user-images.githubusercontent.com/32497323/210913947-57d4f917-452a-4614-a363-0ceb0e315d6b.png)

This is just a normal buffer and in my config is referred to as the `selection list` - it can be bought up using the command `SearchReplaceSingleBufferSelections`, my binding for it looks like: `keymap["r"]["s"] =
  { "<CMD>SearchReplaceSingleBufferSelections<CR>", "SearchReplaceSingleBuffer [s]elction list" }`.

**Comment by roobert** [comment]
I have added some key mappings you might like to try to the docs: https://github.com/roobert/search-replace.nvim#standard-neovim

**Comment by charliie-dev** [comment]
Got it, so `SearchReplaceSingleBufferVisualSelection` still do a full buffer search-replace instead of just within line or within range.
And `SearchReplaceWithinVisualSelectionCWord` can do search-replace within range after visual-selected a block, move cursor to the word and hit my keybinds for `SearchReplaceWithinVisualSelectionCWord`.

As for the `selection list` buffer, I can get sth like this after I hit `SearchReplaceSingleBufferSelections`:
![圖片](https://user-images.githubusercontent.com/32497323/211130237-eaad48cc-3c5d-49f7-9dfc-1c8fc35bc20d.png)

,but not the indexed candidates? If I hit `w`, `e`, `f` or `W`, there's no indexed candidates buffer. Could u share how to config this buffer? I also dig-in your `lnvim` dotfiles, but I couldn't seem to find anything related to open this buffer.

**Comment by charliie-dev** [comment]
> I have added some key mappings you might like to try to the docs: [roobert/search-replace.nvim#standard-neovim](https://github.com/roobert/search-replace.nvim#standard-neovim)

Thanks! That's pretty much the same as I config `search-replace.nvim`'s keymaps lol

![圖片](https://user-images.githubusercontent.com/32497323/211130484-379730b1-ba80-4e54-8815-bec30dd90bc2.png)

**Comment by roobert** [comment]
> Got it, so `SearchReplaceSingleBufferVisualSelection` still do a full buffer search-replace instead of just within line or within range. And `SearchReplaceWithinVisualSelectionCWord` can do search-replace within range after visual-selected a block, move cursor to the word and hit my keybinds for `SearchReplaceWithinVisualSelectionCWord`.

Yes, exactly. There are also commands for `SearchReplaceWithinVisualSelection`and `SearchReplaceWithinVisualSelectionCExpr`, etc. but I didn't add bindings for all of them.

> 
> As for the `selection list` buffer, I can get sth like this after I hit `SearchReplaceSingleBufferSelections`: ![圖片](https://user-images.githubusercontent.com/32497323/211130237-eaad48cc-3c5d-49f7-9dfc-1c8fc35bc20d.png)
> 
> ,but not the indexed candidates? If I hit `w`, `e`, `f` or `W`, there's no indexed candidates buffer. Could u share how to config this buffer? I also dig-in your `lnvim` dotfiles, but I couldn't seem to find anything related to open this buffer.

Ah right, you need to add this: `vim.cmd([[set inccommand=split]])`.

**Comment by charliie-dev** [comment]
Thanks! It work!
For other people looks for this function too, u can use `vim.o.inccommand = "split"` to have the same effect.
